### PR TITLE
Adds more information to the binary's usage

### PR DESCRIPTION
**Pull request by mgdelacroix**
Hi @zimbatm! Sending a simple PR to improve how the usage of the application is displayed so it matches the `README`

### CODE REVIEW

**Comment by zimbatm** [comment]
Thanks!

I am curious, are you using this project? Since I haven't advertised it at all I was pleasantly surprised to see this PR appearing :)

**Comment by mgdelacroix** [comment]
I'm not really using it right now, but definitely plan to for development projects, and I'm more than happy to contribute to it if you have a clear roadmap :)

It popped up in my timeline and decided to take a peek.

**Comment by zimbatm** [comment]
Ah, nice :)

I'm using this in production right now and things are working fine. I am waiting on more real-world data to generate a roadmap.

**Comment by mgdelacroix** [comment]
Awesome! Makes a lot of sense, I'll keep an eye on the project then :)

**Pull request merged**
